<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-MRVJBNT" failures="0" tests="7" name="com.menumitratCommonAPITestScript.UpdateOrderTestScript" time="3.541" errors="1" timestamp="6 Jun 2025 18:22:05 GMT">
  <testcase classname="com.menumitratCommonAPITestScript.UpdateOrderTestScript" name="updateOrderNegativeTest" time="0.088"/>
  <testcase classname="com.menumitratCommonAPITestScript.UpdateOrderTestScript" name="updateOrderNegativeTest" time="0.070"/>
  <testcase classname="com.menumitratCommonAPITestScript.UpdateOrderTestScript" name="updateDineInOrder" time="1.874">
    <error message="Exception in update Dine-In order test: Status code mismatch - Expected: 200, Actual: 400" type="com.menumitra.utilityclass.customException">
      <![CDATA[com.menumitra.utilityclass.customException: Exception in update Dine-In order test: Status code mismatch - Expected: 200, Actual: 400
	at com.menumitratCommonAPITestScript.UpdateOrderTestScript.updateDineInOrder(UpdateOrderTestScript.java:368)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- updateDineInOrder -->
  <testcase classname="com.menumitratCommonAPITestScript.UpdateOrderTestScript" name="updateDeliveryOrder" time="0.334"/>
  <testcase classname="com.menumitratCommonAPITestScript.UpdateOrderTestScript" name="updateDriveThroughOrder" time="0.398"/>
  <testcase classname="com.menumitratCommonAPITestScript.UpdateOrderTestScript" name="updateParcelOrder" time="0.439"/>
  <testcase classname="com.menumitratCommonAPITestScript.UpdateOrderTestScript" name="updateCounterOrder" time="0.338"/>
</testsuite> <!-- com.menumitratCommonAPITestScript.UpdateOrderTestScript -->
